version: '3.9'

services:
  web:
    build: .
    ports:
      - '80:80'
    depends_on:
      - postgres

  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=myexpenses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local